lib: [
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/META" {"META"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/dune-package" {"dune-package"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.a" {"lib/lib.a"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cma" {"lib/lib.cma"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cmi" {"lib/lib.cmi"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cmt" {"lib/lib.cmt"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cmx" {"lib/lib.cmx"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cmxa" {"lib/lib.cmxa"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.cmxs" {"lib/lib.cmxs"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/lib/lib.ml" {"lib/lib.ml"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/opam" {"opam"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/TestFramework.re" {"test/TestFramework.re"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/Tests.re" {"test/Tests.re"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/TreasonTest.a" {"test/TreasonTest.a"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/TreasonTest.cma" {"test/TreasonTest.cma"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/TreasonTest.cmxa" {"test/TreasonTest.cmxa"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/TreasonTest.cmxs" {"test/TreasonTest.cmxs"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest.cmi" {"test/treasonTest.cmi"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest.cmt" {"test/treasonTest.cmt"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest.cmx" {"test/treasonTest.cmx"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest.ml" {"test/treasonTest.ml"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__TestFramework.cmi" {"test/treasonTest__TestFramework.cmi"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__TestFramework.cmt" {"test/treasonTest__TestFramework.cmt"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__TestFramework.cmx" {"test/treasonTest__TestFramework.cmx"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__Tests.cmi" {"test/treasonTest__Tests.cmi"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__Tests.cmt" {"test/treasonTest__Tests.cmt"}
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/lib/treason/test/treasonTest__Tests.cmx" {"test/treasonTest__Tests.cmx"}
]
bin: [
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/bin/RunTests.exe" {"RunTests.exe"}
]
doc: [
  "/Users/cardella/Code/reason/treason/_esy/default/store/b/treason-92601012/install/default/doc/treason/LICENSE.md"
]
